# .rubocop.yml
require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.3
  Exclude:
    - "db/**/*"
    - "Gemfile"
    - "lib/tasks/*.rake"
    - "bin/*"
    - "config/puma.rb"
    - "config/spring.rb"
    - "config/environments/development.rb"
    - "config/environments/production.rb"
    - "spec/spec_helper.rb"
    - "test/**/*"
    - "config.ru"
    - "config/application.rb"
    - "config/boot.rb"
    - "config/importmap.rb"
    - "config/environment.rb"
    - "config/environments/*"
    - "config/initializers/*"
    - "config/route.rb"
    - "spec/rails_helper.rb"
    - "app/views/**/*.jbuilder"
    - "app/controllers/*"
Style/Documentation:
  Enabled: false