version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: development.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file: .env
    environment:
      RAILS_ENV: development
      DB_HOST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: changeme
      REMOTE_DATABASE_URL: postgres://postgres:changeme@postgres:5432/municipes_

  postgres:
    image: postgres:14
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
volumes:
  app:
  postgres:

networks:
  municipes-local:
    external: true