version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: development.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    tmpfs:
      - /tmp/pids/
    env_file: .env
    environment:
      RAILS_ENV: development
      DB_HOST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: changeme
      REMOTE_DATABASE_URL: postgres://postgres:changeme@postgres:5432/municipes_
      PIDFILE: /tmp/pids/server.pid

  postgres:
    image: postgres:14
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  redis:
    image: redis:5.0.7
    container_name: redis-municipes
  sidekiq:
    build:
      context: .
      dockerfile: development.Dockerfile
    command: sleep infinity
    volumes:
      - .:/app
    env_file: .env
    environment:
      RAILS_ENV: development
volumes:
  app:
  postgres:
  redis-data:

networks:
  municipes-local:
    external: true