version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: development.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    links:
      - mailcatcher
      - elasticsearch
      - kibana
    volumes:
      - .:/app
    tmpfs:
      - /tmp/pids/
    environment:
      RAILS_ENV: development
      DB_HOST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: changeme
      PIDFILE: /tmp/pids/server.pid
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOST: elasticsearch:9200
      DATABASE_URL: postgres://postgres:changeme@postgres:5432/municipes
      REDIS_URL: redis://redis:6379/1
      SMTP_ADDRESS: smtp.municipes.org
      SMTP_PORT: 587
      SMTP_DOMAIN: sandbox.municipes.org
      SMTP_FROM: noreply@municipes.org
      EMAIL_TO: bergsonsud@gmail.com
      TWILIO_NUMBER: +18057497008
      TWILIO_ACCOUNT_SID: AC6917fac3fc678cfaa61b09d14fc26965
      TWILIO_AUTH_TOKEN: c07ddeff9d19a179bd038389811d623d
      TWILLO_TO: +5585994171380


  postgres:
    image: postgres:14
#    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5452:5432"
    restart: always
  redis:
    image: redis:5.0.7
    container_name: redis-municipes
  sidekiq:
    build:
      context: .
      dockerfile: development.Dockerfile
    command: sleep infinity
    volumes:
      - .:/app
#    env_file: .env
    environment:
      RAILS_ENV: development
  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
volumes:
  app:
  postgres-data:
  redis-data:
  mailcatcher:
  sidekiq:
  esdata:
    driver: local

networks:
  municipes-local:
    external: true