version: '3'

services:
  app:
    build:
      context: .
      dockerfile: development.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/app
#    env_file: .env
    environment:
      RAILS_ENV: development
      DB_HOST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: changeme

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/varlib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  app:
  postgres:

networks:
  municipes-local:
    driver: brigde